### ISSUE TITLE
FIX - ds metricbeat connection refused to kubernetes nodes

### ISSUE THREAD

**Issue by tuxrulezzz** [tommeramber/Central-Monitoring-and-Logging-Openshift-4#6]
in these two files:
https://github.com/tommeramber/Central-Monitoring-and-Logging-Openshift-4/blob/main/metricbeat-infra/templates/cm-metricbeat-ds-config.yaml
https://github.com/tommeramber/Central-Monitoring-and-Logging-Openshift-4/blob/main/metricbeat-infra/templates/cm-metricbeat-ds-modules.yaml

add:
```yaml
ssl:
  verification_mode: none 
  certificate_authorities:
  - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```

This is because kubelet certificate is signed be internal CA and metricbeat won't be able to verify it

The fix is based on the discussion: https://discuss.elastic.co/t/dial-tcp-kubelet-ip-10250-i-o-timeout-while-trying-to-get-metricbeat-to-talk-to-azure-kubernetes-service/303874/3
